name: MY Build susfsd
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      ksu_fork:
        required: true
        type: string
jobs:
  build-susfs:
    if: github.event.inputs.ksu_fork != 'xxKSU'
    name: Build userspace susfsd
    runs-on: ubuntu-latest
    steps:
    - name: download linuxxpu with patched dir
      uses: actions/download-artifact@v5.0.0
      with:
        name: linuxxpu
        path: .
   
    - name: Build susfsd
      if: github.event.inputs.ksu_fork == 'KSUN'
      working-directory: ./userspace/susfsd
      run: |
        $ANDROID_NDK/ndk-build
      
    - name: Upload a Build Artifact
      if: github.event.inputs.ksu_fork == 'KSUN'
      uses: actions/upload-artifact@v4.6.2
      with:
        name: susfsd-aarch64-linux-android
        path: ./userspace/susfsd/libs

    - name: Build susfs
      if: github.event.inputs.ksu_fork == 'SUKISU'
      working-directory: ./userspace/susfs
      run: |
        $ANDROID_NDK_HOME/ndk-build

    - name: Upload a Build Artifact
      if: github.event.inputs.ksu_fork == 'SUKISU'
      uses: actions/upload-artifact@v4.6.2
      with:
        name: susfs-aarch64-linux-android
        path: ./userspace/susfs/libs
    
